const electronicsProducts = [
  // =========================================================
  // MOBILES
  // =========================================================

  {
    title: "Samsung Galaxy S25 5G",
    description:
      "Premium 5G smartphone with a Dynamic AMOLED display, flagship Snapdragon processor and advanced camera system.",
    color: "Navy",
    price: 79999,
    discountedPrice: 74999,
    stock: 18,
    category: "mobiles",
    specification: {
      Brand: "Samsung",
      Model: "Galaxy S25",
      Display: "6.2-inch Dynamic AMOLED 2X",
      Processor: "Snapdragon 8 Elite",
      RAM: "12 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 10 MP + 12 MP",
      Battery: "4000 mAh",
      OperatingSystem: "Android 15",
    },
  },
  {
    title: "Samsung Galaxy A56 5G",
    description:
      "Mid-range 5G smartphone with a Super AMOLED display, capable cameras and a large battery for everyday performance.",
    color: "Awesome Graphite",
    price: 41999,
    discountedPrice: 37999,
    stock: 25,
    category: "mobiles",
    specification: {
      Brand: "Samsung",
      Model: "Galaxy A56 5G",
      Display: "6.7-inch Super AMOLED 120Hz",
      Processor: "Exynos 1580",
      RAM: "8 GB",
      Storage: "128 GB",
      RearCamera: "50 MP + 12 MP + 5 MP",
      Battery: "5000 mAh",
      OperatingSystem: "Android 15",
    },
  },

  {
    title: "Realme GT 7 5G",
    description:
      "Performance-oriented 5G smartphone with a high-refresh-rate AMOLED display, flagship-grade processor and fast charging.",
    color: "IceSense Blue",
    price: 44999,
    discountedPrice: 40999,
    stock: 20,
    category: "mobiles",
    specification: {
      Brand: "Realme",
      Model: "GT 7",
      Display: "6.78-inch AMOLED 120Hz",
      Processor: "MediaTek Dimensity 9400e",
      RAM: "12 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 8 MP",
      Battery: "7000 mAh",
      OperatingSystem: "Realme UI",
    },
  },

  {
    title: "iQOO Neo 10 5G",
    description:
      "High-performance smartphone designed for gaming and demanding workloads with a high-refresh-rate AMOLED display.",
    color: "Titanium Chrome",
    price: 36999,
    discountedPrice: 33999,
    stock: 23,
    category: "mobiles",
    specification: {
      Brand: "iQOO",
      Model: "Neo 10",
      Display: "6.78-inch AMOLED 144Hz",
      Processor: "Snapdragon 8s Gen 4",
      RAM: "12 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 8 MP",
      Battery: "7000 mAh",
      OperatingSystem: "Funtouch OS",
    },
  },

  {
    title: "OPPO Reno 13 5G",
    description:
      "Stylish 5G smartphone featuring an AMOLED display, AI-powered camera features and fast charging support.",
    color: "Luminous Blue",
    price: 37999,
    discountedPrice: 33999,
    stock: 18,
    category: "mobiles",
    specification: {
      Brand: "OPPO",
      Model: "Reno 13",
      Display: "6.59-inch AMOLED 120Hz",
      Processor: "MediaTek Dimensity 8350",
      RAM: "8 GB",
      Storage: "128 GB",
      RearCamera: "50 MP + 8 MP",
      Battery: "5600 mAh",
      OperatingSystem: "ColorOS 15",
    },
  },

  {
    title: "Realme P3 Pro 5G",
    description:
      "Affordable performance smartphone with a curved AMOLED display, large battery and gaming-focused processor.",
    color: "Galaxy Purple",
    price: 26999,
    discountedPrice: 23999,
    stock: 31,
    category: "mobiles",
    specification: {
      Brand: "Realme",
      Model: "P3 Pro",
      Display: "6.83-inch AMOLED 120Hz",
      Processor: "Snapdragon 7s Gen 3",
      RAM: "8 GB",
      Storage: "128 GB",
      RearCamera: "50 MP + 2 MP",
      Battery: "6000 mAh",
      OperatingSystem: "Realme UI 6",
    },
  },

  {
    title: "Apple iPhone 16",
    description:
      "Powerful smartphone featuring the A18 chip, advanced dual-camera system and Super Retina XDR display.",
    color: "Black",
    price: 79900,
    discountedPrice: 74900,
    stock: 15,
    category: "mobiles",
    specification: {
      Brand: "Apple",
      Model: "iPhone 16",
      Display: "6.1-inch Super Retina XDR",
      Processor: "Apple A18",
      RAM: "8 GB",
      Storage: "128 GB",
      RearCamera: "48 MP + 12 MP",
      Battery: "Up to 22 hours video playback",
      OperatingSystem: "iOS 18",
    },
  },

  {
    title: "OnePlus 13 5G",
    description:
      "Flagship 5G smartphone with a high-refresh-rate AMOLED display, powerful processor and large battery.",
    color: "Midnight Blue",
    price: 69999,
    discountedPrice: 64999,
    stock: 21,
    category: "mobiles",
    specification: {
      Brand: "OnePlus",
      Model: "OnePlus 13",
      Display: "6.82-inch AMOLED 2K",
      Processor: "Snapdragon 8 Elite",
      RAM: "12 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 50 MP + 50 MP",
      Battery: "6000 mAh",
      OperatingSystem: "OxygenOS 15",
    },
  },

  {
    title: "Google Pixel 9",
    description:
      "AI-powered smartphone with an advanced camera system, bright OLED display and clean Android experience.",
    color: "Obsidian",
    price: 79999,
    discountedPrice: 72999,
    stock: 11,
    category: "mobiles",
    specification: {
      Brand: "Google",
      Model: "Pixel 9",
      Display: "6.3-inch OLED",
      Processor: "Google Tensor G4",
      RAM: "12 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 48 MP",
      Battery: "4700 mAh",
      OperatingSystem: "Android 14",
    },
  },

  {
    title: "Nothing Phone (3a) Pro",
    description:
      "Distinctive mid-range smartphone with a smooth AMOLED display, capable camera system and clean Nothing OS experience.",
    color: "Black",
    price: 32999,
    discountedPrice: 29999,
    stock: 26,
    category: "mobiles",
    specification: {
      Brand: "Nothing",
      Model: "Phone (3a) Pro",
      Display: "6.77-inch AMOLED",
      Processor: "Snapdragon 7s Gen 3",
      RAM: "8 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 50 MP + 8 MP",
      Battery: "5000 mAh",
      OperatingSystem: "Nothing OS",
    },
  },

  {
    title: "Xiaomi 14 Civi",
    description:
      "Slim smartphone with a high-resolution AMOLED display, Leica camera system and fast charging support.",
    color: "Matcha Green",
    price: 47999,
    discountedPrice: 39999,
    stock: 19,
    category: "mobiles",
    specification: {
      Brand: "Xiaomi",
      Model: "14 Civi",
      Display: "6.55-inch AMOLED",
      Processor: "Snapdragon 8s Gen 3",
      RAM: "8 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 50 MP + 12 MP",
      Battery: "4700 mAh",
      OperatingSystem: "HyperOS",
    },
  },
  {
    title: "OnePlus Nord 5 5G",
    description:
      "Performance-focused 5G smartphone with a high-refresh-rate AMOLED display, large battery and fast charging.",
    color: "Phantom Grey",
    price: 34999,
    discountedPrice: 31999,
    stock: 24,
    category: "mobiles",
    specification: {
      Brand: "OnePlus",
      Model: "Nord 5",
      Display: "6.83-inch AMOLED 144Hz",
      Processor: "Snapdragon 8s Gen 3",
      RAM: "8 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 8 MP",
      Battery: "6800 mAh",
      OperatingSystem: "OxygenOS",
    },
  },

  {
    title: "Motorola Edge 60 Fusion",
    description:
      "Slim 5G smartphone featuring a curved display, capable camera system and large battery for everyday use.",
    color: "Pantone Slipstream",
    price: 24999,
    discountedPrice: 21999,
    stock: 29,
    category: "mobiles",
    specification: {
      Brand: "Motorola",
      Model: "Edge 60 Fusion",
      Display: "6.67-inch pOLED 120Hz",
      Processor: "MediaTek Dimensity 7400",
      RAM: "8 GB",
      Storage: "256 GB",
      RearCamera: "50 MP + 13 MP",
      Battery: "5500 mAh",
      OperatingSystem: "Android 15",
    },
  },

  {
    title: "Vivo V50 5G",
    description:
      "Stylish 5G smartphone with a high-resolution AMOLED display, portrait photography features and fast charging.",
    color: "Rose Red",
    price: 34999,
    discountedPrice: 31999,
    stock: 22,
    category: "mobiles",
    specification: {
      Brand: "Vivo",
      Model: "V50",
      Display: "6.77-inch AMOLED 120Hz",
      Processor: "Snapdragon 7 Gen 3",
      RAM: "8 GB",
      Storage: "128 GB",
      RearCamera: "50 MP + 50 MP",
      Battery: "6000 mAh",
      OperatingSystem: "Funtouch OS 15",
    },
  },

  // =========================================================
  // LAPTOPS
  // =========================================================

  {
    title: "Apple MacBook Air 13 M4",
    description:
      "Lightweight laptop powered by the Apple M4 chip with a high-resolution Liquid Retina display and long battery life.",
    color: "Midnight",
    price: 99900,
    discountedPrice: 94900,
    stock: 12,
    category: "laptops",
    specification: {
      Brand: "Apple",
      Model: "MacBook Air 13 M4",
      Processor: "Apple M4",
      RAM: "16 GB",
      Storage: "256 GB SSD",
      Display: "13.6-inch Liquid Retina",
      Graphics: "Integrated 8-core GPU",
      Battery: "Up to 18 hours",
      OperatingSystem: "macOS",
    },
  },
  {
    title: "Apple MacBook Pro 14 M4",
    description:
      "Professional laptop powered by the Apple M4 chip with a Liquid Retina XDR display and strong performance for development and creative workloads.",
    color: "Space Black",
    price: 169900,
    discountedPrice: 159900,
    stock: 6,
    category: "laptops",
    specification: {
      Brand: "Apple",
      Model: "MacBook Pro 14 M4",
      Processor: "Apple M4",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "14.2-inch Liquid Retina XDR",
      Graphics: "Integrated 10-core GPU",
      Battery: "Up to 24 hours",
      OperatingSystem: "macOS",
    },
  },

  {
    title: "Lenovo LOQ 15 Gaming Laptop",
    description:
      "Gaming laptop with a dedicated RTX graphics card, high-refresh-rate display and upgraded thermal system.",
    color: "Luna Grey",
    price: 94990,
    discountedPrice: 84990,
    stock: 10,
    category: "laptops",
    specification: {
      Brand: "Lenovo",
      Model: "LOQ 15",
      Processor: "Intel Core i7 13th Gen",
      RAM: "16 GB",
      Storage: "1 TB SSD",
      Display: "15.6-inch Full HD 144Hz",
      Graphics: "NVIDIA GeForce RTX 4060",
      Cooling: "Dual Fan Cooling",
      Battery: "60 Wh",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "Acer Nitro V Gaming Laptop",
    description:
      "Gaming-focused laptop with dedicated NVIDIA graphics, high-refresh-rate display and performance-oriented cooling.",
    color: "Black",
    price: 79990,
    discountedPrice: 71990,
    stock: 11,
    category: "laptops",
    specification: {
      Brand: "Acer",
      Model: "Nitro V",
      Processor: "Intel Core i5 13th Gen",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "15.6-inch Full HD 144Hz",
      Graphics: "NVIDIA GeForce RTX 4050",
      Cooling: "Dual Fan Cooling",
      Connectivity: "Wi-Fi 6",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "Dell Inspiron 15",
    description:
      "Reliable everyday laptop with a large Full HD display, Intel processor and fast SSD storage for productivity.",
    color: "Platinum Silver",
    price: 59990,
    discountedPrice: 52990,
    stock: 21,
    category: "laptops",
    specification: {
      Brand: "Dell",
      Model: "Inspiron 15",
      Processor: "Intel Core i5 13th Gen",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "15.6-inch Full HD",
      Graphics: "Intel Iris Xe",
      Ports: "USB-C, USB-A, HDMI",
      Battery: "54 Wh",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "MSI Modern 14",
    description:
      "Portable productivity laptop with a lightweight design, efficient Intel processor and fast SSD storage.",
    color: "Classic Black",
    price: 57990,
    discountedPrice: 50990,
    stock: 17,
    category: "laptops",
    specification: {
      Brand: "MSI",
      Model: "Modern 14",
      Processor: "Intel Core i5 13th Gen",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "14-inch Full HD IPS",
      Graphics: "Intel Iris Xe",
      Weight: "1.5 kg",
      Connectivity: "Wi-Fi 6",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "Dell Inspiron 14",
    description:
      "Compact productivity laptop with an Intel Core processor, Full HD display and fast SSD storage for work and study.",
    color: "Platinum Silver",
    price: 62990,
    discountedPrice: 55990,
    stock: 14,
    category: "laptops",
    specification: {
      Brand: "Dell",
      Model: "Inspiron 14",
      Processor: "Intel Core i5 13th Gen",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "14-inch Full HD",
      Graphics: "Intel Iris Xe",
      Ports: "USB-C, USB-A, HDMI",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "Acer Aspire 5",
    description:
      "Everyday laptop offering a balanced combination of performance, storage and connectivity for office and home use.",
    color: "Steel Gray",
    price: 57990,
    discountedPrice: 51990,
    stock: 18,
    category: "laptops",
    specification: {
      Brand: "Acer",
      Model: "Aspire 5",
      Processor: "Intel Core i5 13th Gen",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "15.6-inch Full HD IPS",
      Graphics: "Intel Iris Xe",
      Connectivity: "Wi-Fi 6",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "HP Victus Gaming 15",
    description:
      "Gaming laptop with dedicated NVIDIA graphics, high-refresh-rate display and efficient cooling for modern games.",
    color: "Mica Silver",
    price: 84990,
    discountedPrice: 74990,
    stock: 9,
    category: "laptops",
    specification: {
      Brand: "HP",
      Model: "Victus Gaming 15",
      Processor: "AMD Ryzen 7",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "15.6-inch Full HD 144Hz",
      Graphics: "NVIDIA GeForce RTX 4050",
      Cooling: "Dual Fan Cooling",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "ASUS Vivobook 15",
    description:
      "Slim everyday laptop designed for productivity with a bright display, efficient processor and fast SSD storage.",
    color: "Cool Silver",
    price: 54990,
    discountedPrice: 47990,
    stock: 23,
    category: "laptops",
    specification: {
      Brand: "ASUS",
      Model: "Vivobook 15",
      Processor: "Intel Core i5 13th Gen",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "15.6-inch Full HD",
      Graphics: "Intel Iris Xe",
      Weight: "1.7 kg",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "HP Pavilion 14",
    description:
      "Versatile everyday laptop with a compact design, Intel processor, fast SSD storage and Full HD display.",
    color: "Silver",
    price: 67990,
    discountedPrice: 59990,
    stock: 16,
    category: "laptops",
    specification: {
      Brand: "HP",
      Model: "Pavilion 14",
      Processor: "Intel Core i5 13th Gen",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "14-inch Full HD IPS",
      Graphics: "Intel Iris Xe",
      Battery: "Up to 9 hours",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "Lenovo IdeaPad Slim 5",
    description:
      "Slim productivity laptop with an AMD processor, high-resolution display and ample memory for everyday work.",
    color: "Cloud Grey",
    price: 64990,
    discountedPrice: 56990,
    stock: 20,
    category: "laptops",
    specification: {
      Brand: "Lenovo",
      Model: "IdeaPad Slim 5",
      Processor: "AMD Ryzen 7 7730U",
      RAM: "16 GB",
      Storage: "512 GB SSD",
      Display: "15.6-inch Full HD IPS",
      Graphics: "AMD Radeon Graphics",
      Battery: "Up to 10 hours",
      OperatingSystem: "Windows 11",
    },
  },

  {
    title: "ASUS TUF Gaming F15",
    description:
      "Gaming laptop designed for demanding games with a high-refresh-rate display, dedicated graphics and upgraded cooling.",
    color: "Graphite",
    price: 89990,
    discountedPrice: 79990,
    stock: 8,
    category: "laptops",
    specification: {
      Brand: "ASUS",
      Model: "TUF Gaming F15",
      Processor: "Intel Core i7 13th Gen",
      RAM: "16 GB",
      Storage: "1 TB SSD",
      Display: "15.6-inch Full HD 144Hz",
      Graphics: "NVIDIA GeForce RTX 4060",
      Cooling: "Dual Fan Cooling",
      Battery: "90 Wh",
      OperatingSystem: "Windows 11",
    },
  },

  // =========================================================
  // TABLETS
  // =========================================================

  {
    title: "Apple iPad Air M3",
    description:
      "Powerful tablet with the Apple M3 chip, Liquid Retina display and support for productivity and creative workloads.",
    color: "Blue",
    price: 69900,
    discountedPrice: 64900,
    stock: 13,
    category: "tablets",
    specification: {
      Brand: "Apple",
      Model: "iPad Air M3",
      Display: "11-inch Liquid Retina",
      Processor: "Apple M3",
      RAM: "8 GB",
      Storage: "128 GB",
      RearCamera: "12 MP",
      Connectivity: "Wi-Fi",
      OperatingSystem: "iPadOS",
    },
  },
  {
    title: "Samsung Galaxy Tab S9 FE",
    description:
      "Versatile Android tablet with a high-resolution display, S Pen support and large battery for entertainment and productivity.",
    color: "Gray",
    price: 44999,
    discountedPrice: 38999,
    stock: 15,
    category: "tablets",
    specification: {
      Brand: "Samsung",
      Model: "Galaxy Tab S9 FE",
      Display: "10.9-inch LCD 90Hz",
      Processor: "Exynos 1380",
      RAM: "6 GB",
      Storage: "128 GB",
      Battery: "8000 mAh",
      Stylus: "S Pen Included",
      OperatingSystem: "Android",
    },
  },

  {
    title: "Apple iPad 10th Generation",
    description:
      "Versatile iPad with a vibrant Liquid Retina display, capable processor and support for everyday productivity and entertainment.",
    color: "Blue",
    price: 39900,
    discountedPrice: 35900,
    stock: 19,
    category: "tablets",
    specification: {
      Brand: "Apple",
      Model: "iPad 10th Generation",
      Display: "10.9-inch Liquid Retina",
      Processor: "Apple A14 Bionic",
      RAM: "4 GB",
      Storage: "64 GB",
      RearCamera: "12 MP",
      Connectivity: "Wi-Fi",
      OperatingSystem: "iPadOS",
    },
  },

  {
    title: "OnePlus Pad Go 2",
    description:
      "Large-screen tablet designed for entertainment and everyday productivity with a high-resolution display and long battery life.",
    color: "Twin Mint",
    price: 24999,
    discountedPrice: 21999,
    stock: 22,
    category: "tablets",
    specification: {
      Brand: "OnePlus",
      Model: "Pad Go 2",
      Display: "11.6-inch LCD",
      Processor: "MediaTek Dimensity",
      RAM: "8 GB",
      Storage: "128 GB",
      Battery: "10000 mAh",
      Speakers: "Quad Speakers",
      OperatingSystem: "OxygenOS",
    },
  },

  {
    title: "Lenovo Tab M11",
    description:
      "Affordable Android tablet with a large display, quad speakers and stylus support for learning and entertainment.",
    color: "Luna Grey",
    price: 19999,
    discountedPrice: 16999,
    stock: 28,
    category: "tablets",
    specification: {
      Brand: "Lenovo",
      Model: "Tab M11",
      Display: "11-inch 90Hz LCD",
      Processor: "MediaTek Helio G88",
      RAM: "8 GB",
      Storage: "128 GB",
      Battery: "7040 mAh",
      Speakers: "Quad Dolby Atmos Speakers",
      Stylus: "Lenovo Tab Pen Supported",
    },
  },

  {
    title: "Honor Pad X9",
    description:
      "Entertainment-oriented tablet with a large 2K display, slim body and multi-speaker audio system.",
    color: "Space Gray",
    price: 17999,
    discountedPrice: 14999,
    stock: 32,
    category: "tablets",
    specification: {
      Brand: "HONOR",
      Model: "Pad X9",
      Display: "11.5-inch 2K LCD 120Hz",
      Processor: "Snapdragon 685",
      RAM: "4 GB",
      Storage: "128 GB",
      Battery: "7250 mAh",
      Speakers: "Six Speakers",
      OperatingSystem: "MagicOS",
    },
  },

  {
    title: "Xiaomi Pad 7",
    description:
      "Large-screen Android tablet with a high-refresh-rate display, powerful processor and long-lasting battery.",
    color: "Graphite Gray",
    price: 27999,
    discountedPrice: 24999,
    stock: 25,
    category: "tablets",
    specification: {
      Brand: "Xiaomi",
      Model: "Pad 7",
      Display: "11.2-inch LCD 144Hz",
      Processor: "Snapdragon 7+ Gen 3",
      RAM: "8 GB",
      Storage: "128 GB",
      Battery: "8850 mAh",
      Charging: "45 W",
      OperatingSystem: "HyperOS",
    },
  },

  {
    title: "Lenovo Tab P12",
    description:
      "Productivity-focused tablet with a large 12.7-inch display, stereo speakers and support for a digital pen.",
    color: "Storm Grey",
    price: 29999,
    discountedPrice: 25999,
    stock: 16,
    category: "tablets",
    specification: {
      Brand: "Lenovo",
      Model: "Tab P12",
      Display: "12.7-inch 3K LCD",
      Processor: "MediaTek Dimensity 7050",
      RAM: "8 GB",
      Storage: "128 GB",
      Battery: "10200 mAh",
      Speakers: "Quad JBL Speakers",
      Stylus: "Lenovo Tab Pen Plus Supported",
    },
  },

  {
    title: "Redmi Pad Pro",
    description:
      "Entertainment-focused tablet featuring a large high-resolution display, quad speakers and a high-capacity battery.",
    color: "Graphite Gray",
    price: 24999,
    discountedPrice: 21999,
    stock: 27,
    category: "tablets",
    specification: {
      Brand: "Redmi",
      Model: "Pad Pro",
      Display: "12.1-inch LCD 120Hz",
      Processor: "Snapdragon 7s Gen 2",
      RAM: "8 GB",
      Storage: "128 GB",
      Battery: "10000 mAh",
      Speakers: "Quad Speakers",
      OperatingSystem: "HyperOS",
    },
  },

  {
    title: "Samsung Galaxy Tab S10 FE",
    description:
      "Feature-rich Android tablet with a high-resolution display, large battery and S Pen support for productivity.",
    color: "Gray",
    price: 52999,
    discountedPrice: 47999,
    stock: 17,
    category: "tablets",
    specification: {
      Brand: "Samsung",
      Model: "Galaxy Tab S10 FE",
      Display: "10.9-inch LCD",
      Processor: "Exynos 1580",
      RAM: "8 GB",
      Storage: "128 GB",
      Battery: "8000 mAh",
      Stylus: "S Pen Supported",
      OperatingSystem: "Android",
    },
  },

  {
    title: "OnePlus Pad 2",
    description:
      "Large-screen Android tablet designed for entertainment and productivity with a high-refresh-rate display and powerful processor.",
    color: "Nimbus Gray",
    price: 49999,
    discountedPrice: 44999,
    stock: 14,
    category: "tablets",
    specification: {
      Brand: "OnePlus",
      Model: "OnePlus Pad 2",
      Display: "12.1-inch LCD 144Hz",
      Processor: "Snapdragon 8 Gen 3",
      RAM: "8 GB",
      Storage: "128 GB",
      Battery: "9510 mAh",
      Charging: "67 W SUPERVOOC",
      OperatingSystem: "OxygenOS",
    },
  },

  // =========================================================
  // POWER BANKS
  // =========================================================

  {
    title: "Ambrane Powermax 20000mAh Power Bank",
    description:
      "High-capacity power bank with fast charging support and multiple charging ports for smartphones and other devices.",
    color: "Black",
    price: 2499,
    discountedPrice: 1799,
    stock: 35,
    category: "power banks",
    specification: {
      Brand: "Ambrane",
      Model: "Powermax 20000",
      Capacity: "20000 mAh",
      Output: "22.5 W",
      Input: "Type-C",
      Ports: "2 USB-A + 1 USB-C",
      FastCharging: "Supported",
      Compatibility: "Smartphones, tablets and accessories",
    },
  },
  {
    title: "Anker PowerCore 20000",
    description:
      "High-capacity portable power bank designed for reliable everyday charging with multiple safety protections.",
    color: "Black",
    price: 2999,
    discountedPrice: 2499,
    stock: 30,
    category: "power banks",
    specification: {
      Brand: "Anker",
      Model: "PowerCore 20000",
      Capacity: "20000 mAh",
      Output: "20 W",
      Input: "USB-C",
      Ports: "USB-C + USB-A",
      FastCharging: "Supported",
      Protection: "MultiProtect Safety System",
    },
  },

  {
    title: "Portronics Power PRO 20000",
    description:
      "High-capacity power bank with fast charging support, digital battery indication and multiple charging ports.",
    color: "Black",
    price: 2199,
    discountedPrice: 1599,
    stock: 41,
    category: "power banks",
    specification: {
      Brand: "Portronics",
      Model: "Power PRO 20000",
      Capacity: "20000 mAh",
      Output: "22.5 W",
      Input: "Type-C",
      Ports: "2 USB-A + 1 USB-C",
      FastCharging: "Supported",
      Display: "Digital Battery Indicator",
    },
  },

  {
    title: "URBN 10000mAh MagTag Power Bank",
    description:
      "Compact magnetic power bank designed for convenient wireless charging and portable everyday use.",
    color: "Black",
    price: 2499,
    discountedPrice: 1999,
    stock: 27,
    category: "power banks",
    specification: {
      Brand: "URBN",
      Model: "MagTag 10000",
      Capacity: "10000 mAh",
      Output: "20 W",
      WirelessCharging: "Supported",
      Input: "USB-C",
      Ports: "USB-C",
      MagneticMount: "Supported",
      Compatibility: "Compatible Smartphones",
    },
  },

  {
    title: "Mi Power Bank 3i 20000mAh",
    description:
      "Large-capacity power bank offering fast charging and multiple output ports for smartphones and tablets.",
    color: "Black",
    price: 1999,
    discountedPrice: 1699,
    stock: 36,
    category: "power banks",
    specification: {
      Brand: "Xiaomi",
      Model: "Power Bank 3i",
      Capacity: "20000 mAh",
      Output: "18 W",
      Input: "Micro USB + Type-C",
      Ports: "2 USB-A",
      FastCharging: "Supported",
      Protection: "Multiple Safety Protection",
    },
  },

  {
    title: "Stuffcool Snap 10000mAh Power Bank",
    description:
      "Portable wireless power bank with magnetic charging support and USB-C connectivity for everyday convenience.",
    color: "Black",
    price: 2999,
    discountedPrice: 2499,
    stock: 18,
    category: "power banks",
    specification: {
      Brand: "Stuffcool",
      Model: "Snap 10000",
      Capacity: "10000 mAh",
      Output: "20 W",
      WirelessCharging: "15 W",
      Input: "USB-C",
      Ports: "USB-C",
      MagneticMount: "Supported",
      Compatibility: "Magnetic Charging Devices",
    },
  },

  {
    title: "Mi Power Bank 3i 10000mAh",
    description:
      "Compact 10000mAh power bank with dual USB output and convenient Type-C charging support.",
    color: "Black",
    price: 1499,
    discountedPrice: 1199,
    stock: 42,
    category: "power banks",
    specification: {
      Brand: "Xiaomi",
      Model: "Power Bank 3i",
      Capacity: "10000 mAh",
      Output: "18 W",
      Input: "Micro USB + Type-C",
      Ports: "2 USB-A",
      FastCharging: "Supported",
      Protection: "Multiple Safety Protection",
    },
  },
  {
    title: "Portronics Luxcell 20K Power Bank",
    description:
      "High-capacity power bank with fast charging, multiple outputs and a compact design for travel.",
    color: "Black",
    price: 1999,
    discountedPrice: 1499,
    stock: 38,
    category: "power banks",
    specification: {
      Brand: "Portronics",
      Model: "Luxcell 20K",
      Capacity: "20000 mAh",
      Output: "22.5 W",
      Input: "USB-C",
      Ports: "2 USB-A + 1 USB-C",
      FastCharging: "Supported",
      Protection: "Multi-Layer Safety Protection",
    },
  },

  {
    title: "Stuffcool Mega 100W Power Bank",
    description:
      "High-output power bank designed to charge smartphones, tablets and compatible laptops through USB-C.",
    color: "Black",
    price: 6999,
    discountedPrice: 5999,
    stock: 13,
    category: "power banks",
    specification: {
      Brand: "Stuffcool",
      Model: "Mega 100W",
      Capacity: "25000 mAh",
      Output: "100 W",
      Input: "USB-C PD",
      Ports: "2 USB-C + 1 USB-A",
      FastCharging: "USB Power Delivery",
      Display: "Digital Battery Display",
    },
  },

  {
    title: "Zebronics ZEB-PG20000 Power Bank",
    description:
      "Affordable high-capacity power bank with dual USB outputs for charging multiple portable devices.",
    color: "Blue",
    price: 1699,
    discountedPrice: 1299,
    stock: 45,
    category: "power banks",
    specification: {
      Brand: "Zebronics",
      Model: "ZEB-PG20000",
      Capacity: "20000 mAh",
      Output: "22.5 W",
      Input: "Type-C",
      Ports: "2 USB-A + 1 USB-C",
      FastCharging: "Supported",
      Compatibility: "Smartphones and Tablets",
    },
  },

  {
    title: "URBN 20000mAh Nano Power Bank",
    description:
      "Slim high-capacity power bank offering fast charging and compact portability for daily travel and mobile use.",
    color: "Blue",
    price: 2299,
    discountedPrice: 1699,
    stock: 28,
    category: "power banks",
    specification: {
      Brand: "URBN",
      Model: "Nano 20000",
      Capacity: "20000 mAh",
      Output: "22.5 W",
      Input: "Type-C",
      Ports: "USB-A + USB-C",
      FastCharging: "Supported",
      Compatibility: "Smartphones, tablets and earbuds",
    },
  },

  // =========================================================
  // WEARABLES
  // =========================================================

  {
    title: "Samsung Galaxy Watch7",
    description:
      "Premium smartwatch with health tracking, fitness features, AMOLED display and seamless Android integration.",
    color: "Green",
    price: 32999,
    discountedPrice: 28999,
    stock: 10,
    category: "wearables",
    specification: {
      Brand: "Samsung",
      Model: "Galaxy Watch7",
      Display: "1.5-inch Super AMOLED",
      Connectivity: "Bluetooth",
      Sensors: "Heart Rate, ECG, SpO2",
      GPS: "Built-in GPS",
      WaterResistance: "5 ATM",
      Battery: "Up to 40 hours",
      OperatingSystem: "Wear OS",
    },
  },
  {
    title: "Google Pixel Watch 3",
    description:
      "Premium smartwatch with advanced health tracking, bright AMOLED display and integrated GPS for fitness activities.",
    color: "Matte Black",
    price: 39999,
    discountedPrice: 34999,
    stock: 7,
    category: "wearables",
    specification: {
      Brand: "Google",
      Model: "Pixel Watch 3",
      Display: "41mm AMOLED",
      Connectivity: "Bluetooth, Wi-Fi",
      Sensors: "Heart Rate, ECG, SpO2",
      GPS: "Built-in GPS",
      WaterResistance: "5 ATM",
      Battery: "Up to 24 hours",
      OperatingSystem: "Wear OS",
    },
  },

  {
    title: "Garmin Forerunner 165",
    description:
      "Fitness-focused smartwatch designed for runners with GPS tracking, health monitoring and detailed workout metrics.",
    color: "Black",
    price: 31990,
    discountedPrice: 28990,
    stock: 9,
    category: "wearables",
    specification: {
      Brand: "Garmin",
      Model: "Forerunner 165",
      Display: "1.2-inch AMOLED",
      Connectivity: "Bluetooth",
      Sensors: "Heart Rate, Pulse Ox",
      GPS: "Multi-GNSS",
      SportsModes: "25+",
      WaterResistance: "5 ATM",
      Battery: "Up to 11 days",
    },
  },

  {
    title: "Amazfit Active 2",
    description:
      "Smart fitness watch with AMOLED display, health monitoring, GPS tracking and multiple sports modes.",
    color: "Black",
    price: 12999,
    discountedPrice: 10999,
    stock: 21,
    category: "wearables",
    specification: {
      Brand: "Amazfit",
      Model: "Active 2",
      Display: "1.32-inch AMOLED",
      Connectivity: "Bluetooth",
      Sensors: "Heart Rate, SpO2, Sleep",
      GPS: "Built-in GPS",
      SportsModes: "160+",
      WaterResistance: "5 ATM",
      Battery: "Up to 10 days",
    },
  },

  {
    title: "Fire-Boltt Phoenix Ultra",
    description:
      "Affordable smartwatch featuring a large AMOLED display, Bluetooth calling and multiple health tracking functions.",
    color: "Black",
    price: 4999,
    discountedPrice: 3299,
    stock: 39,
    category: "wearables",
    specification: {
      Brand: "Fire-Boltt",
      Model: "Phoenix Ultra",
      Display: "1.39-inch AMOLED",
      Connectivity: "Bluetooth",
      Sensors: "Heart Rate, SpO2, Sleep",
      Calling: "Bluetooth Calling",
      SportsModes: "120+",
      WaterResistance: "IP67",
      Battery: "Up to 7 days",
    },
  },

  {
    title: "CMF Watch Pro 2",
    description:
      "Minimalist smartwatch with a high-resolution AMOLED display, GPS tracking and health monitoring features.",
    color: "Dark Grey",
    price: 5999,
    discountedPrice: 4999,
    stock: 26,
    category: "wearables",
    specification: {
      Brand: "CMF",
      Model: "Watch Pro 2",
      Display: "1.32-inch AMOLED",
      Connectivity: "Bluetooth",
      Sensors: "Heart Rate, SpO2, Sleep",
      GPS: "Built-in GPS",
      Calling: "Bluetooth Calling",
      WaterResistance: "IP68",
      Battery: "Up to 11 days",
    },
  },

  {
    title: "Apple Watch Series 10",
    description:
      "Advanced smartwatch with a thin design, health monitoring features, fitness tracking and seamless iPhone integration.",
    color: "Jet Black",
    price: 46900,
    discountedPrice: 42900,
    stock: 8,
    category: "wearables",
    specification: {
      Brand: "Apple",
      Model: "Watch Series 10",
      Display: "46mm Always-On Retina",
      Connectivity: "Bluetooth, Wi-Fi",
      Sensors: "Heart Rate, ECG, Temperature",
      GPS: "Built-in GPS",
      WaterResistance: "50 Meters",
      Battery: "Up to 18 hours",
      OperatingSystem: "watchOS",
    },
  },

  {
    title: "boAt Lunar Pro Smartwatch",
    description:
      "Affordable smartwatch with an AMOLED display, health tracking features and multiple sports modes.",
    color: "Black",
    price: 4999,
    discountedPrice: 3499,
    stock: 34,
    category: "wearables",
    specification: {
      Brand: "boAt",
      Model: "Lunar Pro",
      Display: "1.43-inch AMOLED",
      Connectivity: "Bluetooth",
      Sensors: "Heart Rate, SpO2, Sleep",
      SportsModes: "100+",
      GPS: "Built-in GPS",
      WaterResistance: "IP68",
      Battery: "Up to 7 days",
    },
  },

  {
    title: "Noise ColorFit Pro 6",
    description:
      "Feature-packed smartwatch with a bright AMOLED display, health monitoring and multiple sports tracking modes.",
    color: "Jet Black",
    price: 5999,
    discountedPrice: 4499,
    stock: 30,
    category: "wearables",
    specification: {
      Brand: "Noise",
      Model: "ColorFit Pro 6",
      Display: "1.96-inch AMOLED",
      Connectivity: "Bluetooth",
      Sensors: "Heart Rate, SpO2, Sleep",
      SportsModes: "100+",
      GPS: "Built-in GPS",
      WaterResistance: "IP68",
      Battery: "Up to 7 days",
    },
  },

  // =========================================================
  // CABLES & ADAPTERS
  // =========================================================

  {
    title: "Anker 543 USB-C to USB-C Cable",
    description:
      "Durable USB-C charging and data cable designed for smartphones, tablets, laptops and other USB-C devices.",
    color: "Black",
    price: 899,
    discountedPrice: 699,
    stock: 50,
    category: "cables & adapters",
    specification: {
      Brand: "Anker",
      Model: "543 USB-C Cable",
      Length: "1.8 m",
      Connector: "USB-C to USB-C",
      ChargingPower: "100 W",
      DataTransfer: "Up to 480 Mbps",
      Compatibility: "USB-C Devices",
      Material: "Braided",
    },
  },
  {
    title: "Portronics Konnect USB-C Cable",
    description:
      "Braided USB-C cable designed for fast charging and reliable data transfer across compatible devices.",
    color: "Black",
    price: 599,
    discountedPrice: 449,
    stock: 65,
    category: "cables & adapters",
    specification: {
      Brand: "Portronics",
      Model: "Konnect",
      Length: "1.2 m",
      Connector: "USB-C to USB-C",
      ChargingPower: "60 W",
      DataTransfer: "Up to 480 Mbps",
      Material: "Braided Nylon",
      Compatibility: "USB-C Smartphones, Tablets and Laptops",
    },
  },

  {
    title: "UGREEN 100W USB-C GaN Charger",
    description:
      "Compact multi-port GaN charger capable of powering laptops, smartphones and tablets simultaneously.",
    color: "Gray",
    price: 6999,
    discountedPrice: 5999,
    stock: 19,
    category: "cables & adapters",
    specification: {
      Brand: "UGREEN",
      Model: "100W GaN Charger",
      Output: "100 W",
      Ports: "3 USB-C + 1 USB-A",
      Technology: "GaN",
      FastCharging: "USB Power Delivery",
      Compatibility: "Laptops, Tablets and Smartphones",
      InputVoltage: "100-240 V",
    },
  },

  {
    title: "Belkin 65W USB-C GaN Charger",
    description:
      "Compact GaN wall charger capable of fast charging smartphones, tablets and compatible laptops through USB-C.",
    color: "White",
    price: 3499,
    discountedPrice: 2999,
    stock: 24,
    category: "cables & adapters",
    specification: {
      Brand: "Belkin",
      Model: "65W GaN Charger",
      Output: "65 W",
      Ports: "2 USB-C",
      Technology: "GaN",
      FastCharging: "Supported",
      Compatibility: "Phones, Tablets and Laptops",
      InputVoltage: "100-240 V",
    },
  },
  {
    title: "Anker 735 65W GaN Charger",
    description:
      "Compact multi-port GaN charger designed to fast charge laptops, tablets and smartphones from a single adapter.",
    color: "Black",
    price: 5999,
    discountedPrice: 4999,
    stock: 20,
    category: "cables & adapters",
    specification: {
      Brand: "Anker",
      Model: "735 Charger",
      Output: "65 W",
      Ports: "2 USB-C + 1 USB-A",
      Technology: "GaN",
      FastCharging: "USB Power Delivery",
      Compatibility: "Laptops, Tablets and Smartphones",
      InputVoltage: "100-240 V",
    },
  },

  {
    title: "Belkin BoostCharge USB-C Cable",
    description:
      "Durable USB-C charging cable designed for fast charging compatible smartphones, tablets and other devices.",
    color: "White",
    price: 999,
    discountedPrice: 799,
    stock: 55,
    category: "cables & adapters",
    specification: {
      Brand: "Belkin",
      Model: "BoostCharge USB-C Cable",
      Length: "1 m",
      Connector: "USB-C to USB-C",
      ChargingPower: "60 W",
      DataTransfer: "Up to 480 Mbps",
      Material: "Durable PVC",
      Compatibility: "USB-C Devices",
    },
  },

  {
    title: "UGREEN USB-C to HDMI Adapter",
    description:
      "Compact adapter that connects USB-C devices to HDMI displays for high-resolution video output.",
    color: "Gray",
    price: 1499,
    discountedPrice: 1199,
    stock: 33,
    category: "cables & adapters",
    specification: {
      Brand: "UGREEN",
      Model: "USB-C HDMI Adapter",
      Connector: "USB-C to HDMI",
      VideoOutput: "Up to 4K",
      RefreshRate: "60Hz",
      Compatibility: "USB-C Laptops and Tablets",
      PlugAndPlay: "Supported",
      Material: "Aluminium Alloy",
    },
  },

  {
    title: "boAt Type-C Fast Charging Cable",
    description:
      "Affordable braided Type-C cable supporting fast charging and reliable data transfer for compatible devices.",
    color: "Black",
    price: 499,
    discountedPrice: 349,
    stock: 70,
    category: "cables & adapters",
    specification: {
      Brand: "boAt",
      Model: "Type-C Fast Charging Cable",
      Length: "1.5 m",
      Connector: "USB-A to USB-C",
      ChargingPower: "60 W",
      DataTransfer: "Up to 480 Mbps",
      Material: "Braided Nylon",
      Compatibility: "Android Smartphones and Accessories",
    },
  },

  {
    title: "Stuffcool 100W USB-C Cable",
    description:
      "High-power USB-C cable designed for fast charging laptops, tablets and smartphones with compatible chargers.",
    color: "Black",
    price: 1299,
    discountedPrice: 999,
    stock: 44,
    category: "cables & adapters",
    specification: {
      Brand: "Stuffcool",
      Model: "100W USB-C Cable",
      Length: "2 m",
      Connector: "USB-C to USB-C",
      ChargingPower: "100 W",
      DataTransfer: "Up to 480 Mbps",
      Material: "Braided",
      Compatibility: "USB-C Smartphones, Tablets and Laptops",
    },
  },
];

console.log(electronicsProducts.length);


module.exports = electronicsProducts;
